### ISSUE TITLE
Idea: Discord Group doing similar

### ISSUE THREAD

**Issue by thomasjpatterson** [entropi/anchormake#1]
Hello Entropi, we are attempting to do something similar and would love for you to join and see how we can work together. https://discord.gg/SnQ3T5rf

**Comment by entropi** [comment]
Excellent, would love to find others interested. I’m on the Discord, but
out of town skiing with the family with very little internet access until Saturday.

 -Chad

**Comment by LazeMSS** [comment]
@thomasjpatterson can I join the discord?

**Comment by lordfiSh** [comment]
> Hello Entropi, we are attempting to do something similar and would love for you to join and see how we can work together. https://discord.gg/SnQ3T5rf

@thomasjpatterson what Discord is this? Link is now invalid
